databases:
  - name: saddharma_prod
    databaseName: saddharma_postgres
    user: sd_admin

services:
  - type: web
    name: saddharma_org
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saddharma_prod
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 