# Generated by Django 4.2.6 on 2023-10-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pages', models.IntegerField(default=0)),
                ('year', models.DateField()),
                ('category_L1', models.CharField(choices=[('L_1_C_1', 'Vinaya'), ('L_1_C_2', 'Sutta'), ('L_1_C_3', 'Ahbhi Dhamma'), ('L_1_C_4', 'Dhamma Sangraha Books'), ('L_1_C_5', 'Pali Grammar'), ('L_1_C_6', 'Other Dhamma Sangraha Books'), ('L_1_C_7', 'Index and Dictionary'), ('L_1_C_8', 'Old Books'), ('L_1_C_8', 'Other Books')], max_length=10)),
                ('category_L2', models.CharField(choices=[('L_2_C_1', 'Tripitaka'), ('L_2_C_2', 'Atuwa'), ('L_2_C_3', 'Tripitaka Teeka'), ('L_2_C_4', 'Sangraha and Vivarana Books'), ('L_2_C_5', 'Vansha Katha'), ('L_2_C_6', 'Buddha Charithaya'), ('L_2_C_7', 'Kosha Grantha'), ('L_2_C_8', 'Chandolankara'), ('L_2_C_9', 'Sandesha Katha'), ('L_2_C_10', 'Chatta Sangayana'), ('L_2_C_11', 'Sanskrutha Bhashawa saha Sahithya'), ('L_2_C_12', 'Waidya Grantha Ha Nighandu'), ('L_2_C_13', 'Tripitaka Suchi'), ('L_2_C_14', 'Shabdha Kosha'), ('L_2_C_15', 'Ven. Rerukane Thero Sangraha Books'), ('L_2_C_16', 'Sandesha'), ('L_2_C_17', 'Sahithyaya'), ('L_2_C_18', 'Bhavana saha karmasthana'), ('L_2_C_19', 'Vaidika Sahithyaya saha Maha kavya'), ('L_2_C_22', 'Other')], max_length=10)),
                ('language', models.CharField(choices=[('L_3_C_1', 'Sinhala'), ('L_3_C_2', 'Pali'), ('L_3_C_2', 'Sanskrutha'), ('L_3_C_2', 'English'), ('L_3_C_2', 'Tamil'), ('L_3_C_2', 'Other')], max_length=10)),
                ('book_code', models.CharField(default='MANAGE THIS', max_length=30)),
                ('storage_link', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('uploaded_date', models.TextField(blank=True)),
                ('approved_by', models.TextField(blank=True)),
                ('approved_date', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.author')),
                ('next_book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source_library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_library', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=300)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='source_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.source_library'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
