# Generated by Django 4.2.6 on 2023-10-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year',
            field=models.DateField(blank=True),
        ),
    ]
