# Generated by Django 4.2.6 on 2023-10-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_author_description_alter_author_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_no', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('author_name', models.CharField(max_length=250)),
                ('published_year', models.DateField(blank=True, null=True)),
                ('pages', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('category1', models.CharField(max_length=30)),
                ('category2', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Source_library',
            new_name='SourceLibrary',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_code',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='catalog_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='next_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
