# Generated by Django 4.2.6 on 2023-10-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booktemp_rename_source_library_sourcelibrary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktemp',
            name='author_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='booktemp',
            name='catalog_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booktemp',
            name='category1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booktemp',
            name='category2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booktemp',
            name='language',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booktemp',
            name='pages',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booktemp',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booktemp',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booktemp',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
