# Generated by Django 4.2.6 on 2023-11-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_book_last_modified_alter_book_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='approved_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
