# Generated by Django 4.2.6 on 2023-11-05 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_book_approved_by_alter_book_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('L3_C1', 'Sinhala'), ('L3_C2', 'Pali'), ('L3_C3', 'Sanskrutha'), ('L3_C4', 'English'), ('L3_C5', 'Tamil'), ('L3_C6', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
