# Generated by Django 4.2.6 on 2023-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_book_category_l1_alter_book_category_l2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
