# Generated by Django 4.2.6 on 2023-11-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_book_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
