# Generated by Django 4.2.6 on 2024-01-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_book_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_L1',
            field=models.CharField(blank=True, choices=[('L1_C1', 'විනය'), ('L1_C2', 'සූත්\u200dර'), ('L1_C3', 'අභිධර්ම'), ('L1_C4', 'ධර්ම සංග්\u200dරහ ග්\u200dරන්ථ'), ('L1_C5', 'පාලි ව්\u200dයාකරණ ග්\u200dරන්ථ'), ('L1_C6', 'ඉපැරණි ග්\u200dරන්ථ'), ('L1_C7', 'වෙනත් ග්\u200dරන්ථ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_L2',
            field=models.CharField(blank=True, choices=[('L1_C1_C1', 'භික්ෂු විනය'), ('L1_C4_C1', 'ධර්ම සංග්\u200dරහ ග්\u200dරන්ථ'), ('L1_C5_C1', 'පාලි ව්\u200dයාකරණ ග්\u200dරන්ථ'), ('L1_C5_C2', 'පාලි භාෂාව'), ('L1_C6_C1', 'පැරණි ධර්ම ග්\u200dරන්ථ'), ('L1_C6_C2', 'බුද්ධ චරිත'), ('L1_C6_C3', 'වංශ කථා හා ඉපැරණි ධර්ම ග්\u200dරන්ථ'), ('L1_C6_C4', 'සංස්කෘත භාෂාව හා සාහිත්\u200dය'), ('L1_C6_C5', 'වෛද්\u200dය ග්\u200dරන්ථ හා නිඝණ්ඩු'), ('L1_C6_C6', 'සිංහල සංදේශ'), ('L1_C6_C7', 'සිංහල සාහිත්\u200dය'), ('L1_C6_C8', 'කෝෂග්\u200dරන්ථ'), ('L1_C6_C9', 'ඡන්දොලංකාර'), ('L1_C6_C10', 'භාවනා කමටහන්'), ('L1_C6_C11', 'වෛදික සාහිත්\u200dය හා මහා කාව්\u200dය'), ('L1_C6_C12', 'සිංහල භාෂාව'), ('L1_C6_C13', 'ත්\u200dරිපිටක සුචි'), ('L1_C6_C14', 'සුචි / ශබ්ධකෝෂ'), ('L2_A1', 'ත්\u200dරිපිටක මූල ග්\u200dරන්ථ'), ('L2_A2', 'සිංහල අටුවා'), ('L2_A3', 'පාලි අටුවා'), ('L2_A4', 'ත්\u200dරිපිටක ටීකා'), ('L2_A5', 'සංග්\u200dරහ ග්\u200dරන්ථ හා විවරණ ග්\u200dරන්ථ'), ('L2_A6', 'ඡට්ට සංගායන ග්\u200dරන්ථ (පාලි)'), ('L2_A7', 'අභිධර්ම'), ('L2_A8', 'බුද්ධ ජයන්ති ත්\u200dරිපිටකය'), ('L2_A9', 'රේරුකානේ නා හිමි ග්\u200dරන්ථ සංග්\u200dරහ'), ('L2_A10', 'වෙනත් ත්\u200dරිපිටක ග්\u200dරන්ථ'), ('L2_A11', 'බෞද්ධ සංස්කෘත මධ්\u200dයස්ථාන මුද්\u200dරණය'), ('L2_A12', 'වංශ කථා හා ඉතිහාසය'), ('L2_A13', 'වෙනත්'), ('L2_A14', 'සූත්\u200dර')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('L3_C1', 'Sinhala / සිංහල'), ('L3_C2', 'Pali / පාලි'), ('L3_C3', 'Sanskrit / සංස්කෘත'), ('L3_C4', 'English / ඉංග්\u200dරීසි'), ('L3_C5', 'Tamil / දෙමළ'), ('L3_C6', 'Burmese / බුරුම'), ('L3_10', 'Other / වෙනත්')], max_length=10, null=True),
        ),
    ]
