# Generated by Django 4.2.6 on 2024-01-07 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_book_category_l1_alter_book_category_l2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='page',
            field=models.IntegerField(null=True),
        ),
    ]
