# Generated by Django 4.2.6 on 2024-07-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comments_parent_comment_alter_comments_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='storage_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
