# Generated by Django 4.2.6 on 2024-07-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_book_storage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
